version: '2'

services:

 db:
  container_name: ld-postgres
  image: postgres:9.3
  ports:
   - 5432:5432
  environment:
   - POSTGRES_DB=logicaldoc
   - POSTGRES_USER=ldoc
   - POSTGRES_PASSWORD=changeme

 logicaldoc:
  depends_on:
   - db
  command: ["./wait-for-postgres.sh", "ld-postgres", "/opt/logicaldoc/start-logicaldoc.sh run", "run"]
  container_name: logicaldoc-ce
  image: logicaldoc/logicaldoc-ce
  ports:
   - 8080:8080
  environment:
   - LDOC_MEMORY=2000
   - DB_HOST=ld-postgres
   - DB_NAME=logicaldoc
   - DB_USER=ldoc
   - DB_PASSWORD=changeme
   - DB_PORT=5432
   - DB_ENGINE=postgres

